//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbhtp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Comment
    {
        public int CmtId { get; set; }
        public int BlogId { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual tb_Blog tb_Blog { get; set; }
    }
}
