//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbhtp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Product
    {
        public int ProductdID { get; set; }
        public string Title { get; set; }
        public string Alias { get; set; }
        public string Image { get; set; }
        public string Price { get; set; }
        public string PriceSale { get; set; }
        public Nullable<int> Quantity { get; set; }
        public bool IsNew { get; set; }
        public bool IsBestSeller { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CategoryProductId { get; set; }
        public string describe { get; set; }
    
        public virtual tb_CategoryProduct tb_CategoryProduct { get; set; }
    }
}
